#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChuyenDe
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyChuyenDe")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHUYENDE(CHUYENDE instance);
    partial void UpdateCHUYENDE(CHUYENDE instance);
    partial void DeleteCHUYENDE(CHUYENDE instance);
    partial void InsertDANGKY(DANGKY instance);
    partial void UpdateDANGKY(DANGKY instance);
    partial void DeleteDANGKY(DANGKY instance);
    partial void InsertDANGKYNHOM(DANGKYNHOM instance);
    partial void UpdateDANGKYNHOM(DANGKYNHOM instance);
    partial void DeleteDANGKYNHOM(DANGKYNHOM instance);
    partial void InsertGIAOVIEN(GIAOVIEN instance);
    partial void UpdateGIAOVIEN(GIAOVIEN instance);
    partial void DeleteGIAOVIEN(GIAOVIEN instance);
    partial void InsertGIAOVU(GIAOVU instance);
    partial void UpdateGIAOVU(GIAOVU instance);
    partial void DeleteGIAOVU(GIAOVU instance);
    partial void InsertNGANH(NGANH instance);
    partial void UpdateNGANH(NGANH instance);
    partial void DeleteNGANH(NGANH instance);
    partial void InsertNHOM(NHOM instance);
    partial void UpdateNHOM(NHOM instance);
    partial void DeleteNHOM(NHOM instance);
    partial void InsertSINHVIEN(SINHVIEN instance);
    partial void UpdateSINHVIEN(SINHVIEN instance);
    partial void DeleteSINHVIEN(SINHVIEN instance);
    partial void InsertMOCHUYENDE(MOCHUYENDE instance);
    partial void UpdateMOCHUYENDE(MOCHUYENDE instance);
    partial void DeleteMOCHUYENDE(MOCHUYENDE instance);
    partial void InsertTAIKHOAN(TAIKHOAN instance);
    partial void UpdateTAIKHOAN(TAIKHOAN instance);
    partial void DeleteTAIKHOAN(TAIKHOAN instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::QuanLyChuyenDe.Properties.Settings.Default.QuanLyChuyenDeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHUYENDE> CHUYENDEs
		{
			get
			{
				return this.GetTable<CHUYENDE>();
			}
		}
		
		public System.Data.Linq.Table<DANGKY> DANGKies
		{
			get
			{
				return this.GetTable<DANGKY>();
			}
		}
		
		public System.Data.Linq.Table<DANGKYNHOM> DANGKYNHOMs
		{
			get
			{
				return this.GetTable<DANGKYNHOM>();
			}
		}
		
		public System.Data.Linq.Table<GIAOVIEN> GIAOVIENs
		{
			get
			{
				return this.GetTable<GIAOVIEN>();
			}
		}
		
		public System.Data.Linq.Table<GIAOVU> GIAOVUs
		{
			get
			{
				return this.GetTable<GIAOVU>();
			}
		}
		
		public System.Data.Linq.Table<NGANH> NGANHs
		{
			get
			{
				return this.GetTable<NGANH>();
			}
		}
		
		public System.Data.Linq.Table<NHOM> NHOMs
		{
			get
			{
				return this.GetTable<NHOM>();
			}
		}
		
		public System.Data.Linq.Table<SINHVIEN> SINHVIENs
		{
			get
			{
				return this.GetTable<SINHVIEN>();
			}
		}
		
		public System.Data.Linq.Table<MOCHUYENDE> MOCHUYENDEs
		{
			get
			{
				return this.GetTable<MOCHUYENDE>();
			}
		}
		
		public System.Data.Linq.Table<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this.GetTable<TAIKHOAN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUYENDE")]
	public partial class CHUYENDE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MACD;
		
		private System.Nullable<int> _MANGANH;
		
		private string _TENCD;
		
		private System.Nullable<int> _SOHVMAX;
		
		private EntityRef<MOCHUYENDE> _MOCHUYENDE;
		
		private EntityRef<NGANH> _NGANH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACDChanging(int value);
    partial void OnMACDChanged();
    partial void OnMANGANHChanging(System.Nullable<int> value);
    partial void OnMANGANHChanged();
    partial void OnTENCDChanging(string value);
    partial void OnTENCDChanged();
    partial void OnSOHVMAXChanging(System.Nullable<int> value);
    partial void OnSOHVMAXChanged();
    #endregion
		
		public CHUYENDE()
		{
			this._MOCHUYENDE = default(EntityRef<MOCHUYENDE>);
			this._NGANH = default(EntityRef<NGANH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MACD
		{
			get
			{
				return this._MACD;
			}
			set
			{
				if ((this._MACD != value))
				{
					this.OnMACDChanging(value);
					this.SendPropertyChanging();
					this._MACD = value;
					this.SendPropertyChanged("MACD");
					this.OnMACDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANGANH", DbType="Int")]
		public System.Nullable<int> MANGANH
		{
			get
			{
				return this._MANGANH;
			}
			set
			{
				if ((this._MANGANH != value))
				{
					if (this._NGANH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANGANHChanging(value);
					this.SendPropertyChanging();
					this._MANGANH = value;
					this.SendPropertyChanged("MANGANH");
					this.OnMANGANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCD", DbType="NVarChar(50)")]
		public string TENCD
		{
			get
			{
				return this._TENCD;
			}
			set
			{
				if ((this._TENCD != value))
				{
					this.OnTENCDChanging(value);
					this.SendPropertyChanging();
					this._TENCD = value;
					this.SendPropertyChanged("TENCD");
					this.OnTENCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOHVMAX", DbType="Int")]
		public System.Nullable<int> SOHVMAX
		{
			get
			{
				return this._SOHVMAX;
			}
			set
			{
				if ((this._SOHVMAX != value))
				{
					this.OnSOHVMAXChanging(value);
					this.SendPropertyChanging();
					this._SOHVMAX = value;
					this.SendPropertyChanged("SOHVMAX");
					this.OnSOHVMAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUYENDE_MOCHUYENDE", Storage="_MOCHUYENDE", ThisKey="MACD", OtherKey="MACD", IsUnique=true, IsForeignKey=false)]
		public MOCHUYENDE MOCHUYENDE
		{
			get
			{
				return this._MOCHUYENDE.Entity;
			}
			set
			{
				MOCHUYENDE previousValue = this._MOCHUYENDE.Entity;
				if (((previousValue != value) 
							|| (this._MOCHUYENDE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MOCHUYENDE.Entity = null;
						previousValue.CHUYENDE = null;
					}
					this._MOCHUYENDE.Entity = value;
					if ((value != null))
					{
						value.CHUYENDE = this;
					}
					this.SendPropertyChanged("MOCHUYENDE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGANH_CHUYENDE", Storage="_NGANH", ThisKey="MANGANH", OtherKey="MANGANH", IsForeignKey=true)]
		public NGANH NGANH
		{
			get
			{
				return this._NGANH.Entity;
			}
			set
			{
				NGANH previousValue = this._NGANH.Entity;
				if (((previousValue != value) 
							|| (this._NGANH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NGANH.Entity = null;
						previousValue.CHUYENDEs.Remove(this);
					}
					this._NGANH.Entity = value;
					if ((value != null))
					{
						value.CHUYENDEs.Add(this);
						this._MANGANH = value.MANGANH;
					}
					else
					{
						this._MANGANH = default(Nullable<int>);
					}
					this.SendPropertyChanged("NGANH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANGKY")]
	public partial class DANGKY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MSSV;
		
		private int _MACD;
		
		private System.Nullable<int> _NAM;
		
		private System.Nullable<int> _HOCKY;
		
		private System.Nullable<int> _DIEM;
		
		private EntityRef<SINHVIEN> _SINHVIEN;
		
		private EntityRef<MOCHUYENDE> _MOCHUYENDE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMSSVChanging(int value);
    partial void OnMSSVChanged();
    partial void OnMACDChanging(int value);
    partial void OnMACDChanged();
    partial void OnNAMChanging(System.Nullable<int> value);
    partial void OnNAMChanged();
    partial void OnHOCKYChanging(System.Nullable<int> value);
    partial void OnHOCKYChanged();
    partial void OnDIEMChanging(System.Nullable<int> value);
    partial void OnDIEMChanged();
    #endregion
		
		public DANGKY()
		{
			this._SINHVIEN = default(EntityRef<SINHVIEN>);
			this._MOCHUYENDE = default(EntityRef<MOCHUYENDE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSSV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MSSV
		{
			get
			{
				return this._MSSV;
			}
			set
			{
				if ((this._MSSV != value))
				{
					if (this._SINHVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMSSVChanging(value);
					this.SendPropertyChanging();
					this._MSSV = value;
					this.SendPropertyChanged("MSSV");
					this.OnMSSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACD", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MACD
		{
			get
			{
				return this._MACD;
			}
			set
			{
				if ((this._MACD != value))
				{
					if (this._MOCHUYENDE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMACDChanging(value);
					this.SendPropertyChanging();
					this._MACD = value;
					this.SendPropertyChanged("MACD");
					this.OnMACDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAM", DbType="Int")]
		public System.Nullable<int> NAM
		{
			get
			{
				return this._NAM;
			}
			set
			{
				if ((this._NAM != value))
				{
					this.OnNAMChanging(value);
					this.SendPropertyChanging();
					this._NAM = value;
					this.SendPropertyChanged("NAM");
					this.OnNAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOCKY", DbType="Int")]
		public System.Nullable<int> HOCKY
		{
			get
			{
				return this._HOCKY;
			}
			set
			{
				if ((this._HOCKY != value))
				{
					this.OnHOCKYChanging(value);
					this.SendPropertyChanging();
					this._HOCKY = value;
					this.SendPropertyChanged("HOCKY");
					this.OnHOCKYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEM", DbType="Int")]
		public System.Nullable<int> DIEM
		{
			get
			{
				return this._DIEM;
			}
			set
			{
				if ((this._DIEM != value))
				{
					this.OnDIEMChanging(value);
					this.SendPropertyChanging();
					this._DIEM = value;
					this.SendPropertyChanged("DIEM");
					this.OnDIEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SINHVIEN_DANGKY", Storage="_SINHVIEN", ThisKey="MSSV", OtherKey="MSSV", IsForeignKey=true)]
		public SINHVIEN SINHVIEN
		{
			get
			{
				return this._SINHVIEN.Entity;
			}
			set
			{
				SINHVIEN previousValue = this._SINHVIEN.Entity;
				if (((previousValue != value) 
							|| (this._SINHVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SINHVIEN.Entity = null;
						previousValue.DANGKies.Remove(this);
					}
					this._SINHVIEN.Entity = value;
					if ((value != null))
					{
						value.DANGKies.Add(this);
						this._MSSV = value.MSSV;
					}
					else
					{
						this._MSSV = default(int);
					}
					this.SendPropertyChanged("SINHVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MOCHUYENDE_DANGKY", Storage="_MOCHUYENDE", ThisKey="MACD", OtherKey="MACD", IsForeignKey=true)]
		public MOCHUYENDE MOCHUYENDE
		{
			get
			{
				return this._MOCHUYENDE.Entity;
			}
			set
			{
				MOCHUYENDE previousValue = this._MOCHUYENDE.Entity;
				if (((previousValue != value) 
							|| (this._MOCHUYENDE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MOCHUYENDE.Entity = null;
						previousValue.DANGKies.Remove(this);
					}
					this._MOCHUYENDE.Entity = value;
					if ((value != null))
					{
						value.DANGKies.Add(this);
						this._MACD = value.MACD;
					}
					else
					{
						this._MACD = default(int);
					}
					this.SendPropertyChanged("MOCHUYENDE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANGKYNHOM")]
	public partial class DANGKYNHOM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MANHOM;
		
		private int _MSSV;
		
		private EntityRef<NHOM> _NHOM;
		
		private EntityRef<SINHVIEN> _SINHVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANHOMChanging(int value);
    partial void OnMANHOMChanged();
    partial void OnMSSVChanging(int value);
    partial void OnMSSVChanged();
    #endregion
		
		public DANGKYNHOM()
		{
			this._NHOM = default(EntityRef<NHOM>);
			this._SINHVIEN = default(EntityRef<SINHVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHOM", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MANHOM
		{
			get
			{
				return this._MANHOM;
			}
			set
			{
				if ((this._MANHOM != value))
				{
					if (this._NHOM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANHOMChanging(value);
					this.SendPropertyChanging();
					this._MANHOM = value;
					this.SendPropertyChanged("MANHOM");
					this.OnMANHOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSSV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MSSV
		{
			get
			{
				return this._MSSV;
			}
			set
			{
				if ((this._MSSV != value))
				{
					if (this._SINHVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMSSVChanging(value);
					this.SendPropertyChanging();
					this._MSSV = value;
					this.SendPropertyChanged("MSSV");
					this.OnMSSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHOM_DANGKYNHOM", Storage="_NHOM", ThisKey="MANHOM", OtherKey="MANHOM", IsForeignKey=true)]
		public NHOM NHOM
		{
			get
			{
				return this._NHOM.Entity;
			}
			set
			{
				NHOM previousValue = this._NHOM.Entity;
				if (((previousValue != value) 
							|| (this._NHOM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHOM.Entity = null;
						previousValue.DANGKYNHOMs.Remove(this);
					}
					this._NHOM.Entity = value;
					if ((value != null))
					{
						value.DANGKYNHOMs.Add(this);
						this._MANHOM = value.MANHOM;
					}
					else
					{
						this._MANHOM = default(int);
					}
					this.SendPropertyChanged("NHOM");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SINHVIEN_DANGKYNHOM", Storage="_SINHVIEN", ThisKey="MSSV", OtherKey="MSSV", IsForeignKey=true)]
		public SINHVIEN SINHVIEN
		{
			get
			{
				return this._SINHVIEN.Entity;
			}
			set
			{
				SINHVIEN previousValue = this._SINHVIEN.Entity;
				if (((previousValue != value) 
							|| (this._SINHVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SINHVIEN.Entity = null;
						previousValue.DANGKYNHOMs.Remove(this);
					}
					this._SINHVIEN.Entity = value;
					if ((value != null))
					{
						value.DANGKYNHOMs.Add(this);
						this._MSSV = value.MSSV;
					}
					else
					{
						this._MSSV = default(int);
					}
					this.SendPropertyChanged("SINHVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GIAOVIEN")]
	public partial class GIAOVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAGV;
		
		private string _USERNAME;
		
		private string _TENGV;
		
		private EntityRef<TAIKHOAN> _TAIKHOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAGVChanging(int value);
    partial void OnMAGVChanged();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    partial void OnTENGVChanging(string value);
    partial void OnTENGVChanged();
    #endregion
		
		public GIAOVIEN()
		{
			this._TAIKHOAN = default(EntityRef<TAIKHOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAGV
		{
			get
			{
				return this._MAGV;
			}
			set
			{
				if ((this._MAGV != value))
				{
					this.OnMAGVChanging(value);
					this.SendPropertyChanging();
					this._MAGV = value;
					this.SendPropertyChanged("MAGV");
					this.OnMAGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(50)")]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					if (this._TAIKHOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENGV", DbType="NVarChar(50)")]
		public string TENGV
		{
			get
			{
				return this._TENGV;
			}
			set
			{
				if ((this._TENGV != value))
				{
					this.OnTENGVChanging(value);
					this.SendPropertyChanging();
					this._TENGV = value;
					this.SendPropertyChanged("TENGV");
					this.OnTENGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_GIAOVIEN", Storage="_TAIKHOAN", ThisKey="USERNAME", OtherKey="USERNAME", IsForeignKey=true)]
		public TAIKHOAN TAIKHOAN
		{
			get
			{
				return this._TAIKHOAN.Entity;
			}
			set
			{
				TAIKHOAN previousValue = this._TAIKHOAN.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOAN.Entity = null;
						previousValue.GIAOVIENs.Remove(this);
					}
					this._TAIKHOAN.Entity = value;
					if ((value != null))
					{
						value.GIAOVIENs.Add(this);
						this._USERNAME = value.USERNAME;
					}
					else
					{
						this._USERNAME = default(string);
					}
					this.SendPropertyChanged("TAIKHOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GIAOVU")]
	public partial class GIAOVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAGIAOVU;
		
		private string _USERNAME;
		
		private EntitySet<MOCHUYENDE> _MOCHUYENDEs;
		
		private EntityRef<TAIKHOAN> _TAIKHOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAGIAOVUChanging(int value);
    partial void OnMAGIAOVUChanged();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    #endregion
		
		public GIAOVU()
		{
			this._MOCHUYENDEs = new EntitySet<MOCHUYENDE>(new Action<MOCHUYENDE>(this.attach_MOCHUYENDEs), new Action<MOCHUYENDE>(this.detach_MOCHUYENDEs));
			this._TAIKHOAN = default(EntityRef<TAIKHOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGIAOVU", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAGIAOVU
		{
			get
			{
				return this._MAGIAOVU;
			}
			set
			{
				if ((this._MAGIAOVU != value))
				{
					this.OnMAGIAOVUChanging(value);
					this.SendPropertyChanging();
					this._MAGIAOVU = value;
					this.SendPropertyChanged("MAGIAOVU");
					this.OnMAGIAOVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(50)")]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					if (this._TAIKHOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAOVU_MOCHUYENDE", Storage="_MOCHUYENDEs", ThisKey="MAGIAOVU", OtherKey="MAGIAOVU")]
		public EntitySet<MOCHUYENDE> MOCHUYENDEs
		{
			get
			{
				return this._MOCHUYENDEs;
			}
			set
			{
				this._MOCHUYENDEs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_GIAOVU", Storage="_TAIKHOAN", ThisKey="USERNAME", OtherKey="USERNAME", IsForeignKey=true)]
		public TAIKHOAN TAIKHOAN
		{
			get
			{
				return this._TAIKHOAN.Entity;
			}
			set
			{
				TAIKHOAN previousValue = this._TAIKHOAN.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOAN.Entity = null;
						previousValue.GIAOVUs.Remove(this);
					}
					this._TAIKHOAN.Entity = value;
					if ((value != null))
					{
						value.GIAOVUs.Add(this);
						this._USERNAME = value.USERNAME;
					}
					else
					{
						this._USERNAME = default(string);
					}
					this.SendPropertyChanged("TAIKHOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MOCHUYENDEs(MOCHUYENDE entity)
		{
			this.SendPropertyChanging();
			entity.GIAOVU = this;
		}
		
		private void detach_MOCHUYENDEs(MOCHUYENDE entity)
		{
			this.SendPropertyChanging();
			entity.GIAOVU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGANH")]
	public partial class NGANH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MANGANH;
		
		private string _TENNGANH;
		
		private System.Nullable<int> _SOHV;
		
		private EntitySet<CHUYENDE> _CHUYENDEs;
		
		private EntitySet<SINHVIEN> _SINHVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANGANHChanging(int value);
    partial void OnMANGANHChanged();
    partial void OnTENNGANHChanging(string value);
    partial void OnTENNGANHChanged();
    partial void OnSOHVChanging(System.Nullable<int> value);
    partial void OnSOHVChanged();
    #endregion
		
		public NGANH()
		{
			this._CHUYENDEs = new EntitySet<CHUYENDE>(new Action<CHUYENDE>(this.attach_CHUYENDEs), new Action<CHUYENDE>(this.detach_CHUYENDEs));
			this._SINHVIENs = new EntitySet<SINHVIEN>(new Action<SINHVIEN>(this.attach_SINHVIENs), new Action<SINHVIEN>(this.detach_SINHVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANGANH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MANGANH
		{
			get
			{
				return this._MANGANH;
			}
			set
			{
				if ((this._MANGANH != value))
				{
					this.OnMANGANHChanging(value);
					this.SendPropertyChanging();
					this._MANGANH = value;
					this.SendPropertyChanged("MANGANH");
					this.OnMANGANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNGANH", DbType="NVarChar(50)")]
		public string TENNGANH
		{
			get
			{
				return this._TENNGANH;
			}
			set
			{
				if ((this._TENNGANH != value))
				{
					this.OnTENNGANHChanging(value);
					this.SendPropertyChanging();
					this._TENNGANH = value;
					this.SendPropertyChanged("TENNGANH");
					this.OnTENNGANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOHV", DbType="Int")]
		public System.Nullable<int> SOHV
		{
			get
			{
				return this._SOHV;
			}
			set
			{
				if ((this._SOHV != value))
				{
					this.OnSOHVChanging(value);
					this.SendPropertyChanging();
					this._SOHV = value;
					this.SendPropertyChanged("SOHV");
					this.OnSOHVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGANH_CHUYENDE", Storage="_CHUYENDEs", ThisKey="MANGANH", OtherKey="MANGANH")]
		public EntitySet<CHUYENDE> CHUYENDEs
		{
			get
			{
				return this._CHUYENDEs;
			}
			set
			{
				this._CHUYENDEs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGANH_SINHVIEN", Storage="_SINHVIENs", ThisKey="MANGANH", OtherKey="MANGANH")]
		public EntitySet<SINHVIEN> SINHVIENs
		{
			get
			{
				return this._SINHVIENs;
			}
			set
			{
				this._SINHVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHUYENDEs(CHUYENDE entity)
		{
			this.SendPropertyChanging();
			entity.NGANH = this;
		}
		
		private void detach_CHUYENDEs(CHUYENDE entity)
		{
			this.SendPropertyChanging();
			entity.NGANH = null;
		}
		
		private void attach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.NGANH = this;
		}
		
		private void detach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.NGANH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHOM")]
	public partial class NHOM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MANHOM;
		
		private string _TENNHOM;
		
		private EntitySet<DANGKYNHOM> _DANGKYNHOMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANHOMChanging(int value);
    partial void OnMANHOMChanged();
    partial void OnTENNHOMChanging(string value);
    partial void OnTENNHOMChanged();
    #endregion
		
		public NHOM()
		{
			this._DANGKYNHOMs = new EntitySet<DANGKYNHOM>(new Action<DANGKYNHOM>(this.attach_DANGKYNHOMs), new Action<DANGKYNHOM>(this.detach_DANGKYNHOMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHOM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MANHOM
		{
			get
			{
				return this._MANHOM;
			}
			set
			{
				if ((this._MANHOM != value))
				{
					this.OnMANHOMChanging(value);
					this.SendPropertyChanging();
					this._MANHOM = value;
					this.SendPropertyChanged("MANHOM");
					this.OnMANHOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNHOM", DbType="NVarChar(50)")]
		public string TENNHOM
		{
			get
			{
				return this._TENNHOM;
			}
			set
			{
				if ((this._TENNHOM != value))
				{
					this.OnTENNHOMChanging(value);
					this.SendPropertyChanging();
					this._TENNHOM = value;
					this.SendPropertyChanged("TENNHOM");
					this.OnTENNHOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHOM_DANGKYNHOM", Storage="_DANGKYNHOMs", ThisKey="MANHOM", OtherKey="MANHOM")]
		public EntitySet<DANGKYNHOM> DANGKYNHOMs
		{
			get
			{
				return this._DANGKYNHOMs;
			}
			set
			{
				this._DANGKYNHOMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DANGKYNHOMs(DANGKYNHOM entity)
		{
			this.SendPropertyChanging();
			entity.NHOM = this;
		}
		
		private void detach_DANGKYNHOMs(DANGKYNHOM entity)
		{
			this.SendPropertyChanging();
			entity.NHOM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SINHVIEN")]
	public partial class SINHVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MSSV;
		
		private System.Nullable<int> _MANGANH;
		
		private string _USERNAME;
		
		private string _TENSV;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _PHAI;
		
		private string _DIACHI;
		
		private EntitySet<DANGKY> _DANGKies;
		
		private EntitySet<DANGKYNHOM> _DANGKYNHOMs;
		
		private EntityRef<NGANH> _NGANH;
		
		private EntityRef<TAIKHOAN> _TAIKHOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMSSVChanging(int value);
    partial void OnMSSVChanged();
    partial void OnMANGANHChanging(System.Nullable<int> value);
    partial void OnMANGANHChanged();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    partial void OnTENSVChanging(string value);
    partial void OnTENSVChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnPHAIChanging(string value);
    partial void OnPHAIChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    #endregion
		
		public SINHVIEN()
		{
			this._DANGKies = new EntitySet<DANGKY>(new Action<DANGKY>(this.attach_DANGKies), new Action<DANGKY>(this.detach_DANGKies));
			this._DANGKYNHOMs = new EntitySet<DANGKYNHOM>(new Action<DANGKYNHOM>(this.attach_DANGKYNHOMs), new Action<DANGKYNHOM>(this.detach_DANGKYNHOMs));
			this._NGANH = default(EntityRef<NGANH>);
			this._TAIKHOAN = default(EntityRef<TAIKHOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSSV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MSSV
		{
			get
			{
				return this._MSSV;
			}
			set
			{
				if ((this._MSSV != value))
				{
					this.OnMSSVChanging(value);
					this.SendPropertyChanging();
					this._MSSV = value;
					this.SendPropertyChanged("MSSV");
					this.OnMSSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANGANH", DbType="Int")]
		public System.Nullable<int> MANGANH
		{
			get
			{
				return this._MANGANH;
			}
			set
			{
				if ((this._MANGANH != value))
				{
					if (this._NGANH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANGANHChanging(value);
					this.SendPropertyChanging();
					this._MANGANH = value;
					this.SendPropertyChanged("MANGANH");
					this.OnMANGANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(50)")]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					if (this._TAIKHOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENSV", DbType="NVarChar(50)")]
		public string TENSV
		{
			get
			{
				return this._TENSV;
			}
			set
			{
				if ((this._TENSV != value))
				{
					this.OnTENSVChanging(value);
					this.SendPropertyChanging();
					this._TENSV = value;
					this.SendPropertyChanged("TENSV");
					this.OnTENSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHAI", DbType="NVarChar(20)")]
		public string PHAI
		{
			get
			{
				return this._PHAI;
			}
			set
			{
				if ((this._PHAI != value))
				{
					this.OnPHAIChanging(value);
					this.SendPropertyChanging();
					this._PHAI = value;
					this.SendPropertyChanged("PHAI");
					this.OnPHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(256)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SINHVIEN_DANGKY", Storage="_DANGKies", ThisKey="MSSV", OtherKey="MSSV")]
		public EntitySet<DANGKY> DANGKies
		{
			get
			{
				return this._DANGKies;
			}
			set
			{
				this._DANGKies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SINHVIEN_DANGKYNHOM", Storage="_DANGKYNHOMs", ThisKey="MSSV", OtherKey="MSSV")]
		public EntitySet<DANGKYNHOM> DANGKYNHOMs
		{
			get
			{
				return this._DANGKYNHOMs;
			}
			set
			{
				this._DANGKYNHOMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGANH_SINHVIEN", Storage="_NGANH", ThisKey="MANGANH", OtherKey="MANGANH", IsForeignKey=true)]
		public NGANH NGANH
		{
			get
			{
				return this._NGANH.Entity;
			}
			set
			{
				NGANH previousValue = this._NGANH.Entity;
				if (((previousValue != value) 
							|| (this._NGANH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NGANH.Entity = null;
						previousValue.SINHVIENs.Remove(this);
					}
					this._NGANH.Entity = value;
					if ((value != null))
					{
						value.SINHVIENs.Add(this);
						this._MANGANH = value.MANGANH;
					}
					else
					{
						this._MANGANH = default(Nullable<int>);
					}
					this.SendPropertyChanged("NGANH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_SINHVIEN", Storage="_TAIKHOAN", ThisKey="USERNAME", OtherKey="USERNAME", IsForeignKey=true)]
		public TAIKHOAN TAIKHOAN
		{
			get
			{
				return this._TAIKHOAN.Entity;
			}
			set
			{
				TAIKHOAN previousValue = this._TAIKHOAN.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOAN.Entity = null;
						previousValue.SINHVIENs.Remove(this);
					}
					this._TAIKHOAN.Entity = value;
					if ((value != null))
					{
						value.SINHVIENs.Add(this);
						this._USERNAME = value.USERNAME;
					}
					else
					{
						this._USERNAME = default(string);
					}
					this.SendPropertyChanged("TAIKHOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DANGKies(DANGKY entity)
		{
			this.SendPropertyChanging();
			entity.SINHVIEN = this;
		}
		
		private void detach_DANGKies(DANGKY entity)
		{
			this.SendPropertyChanging();
			entity.SINHVIEN = null;
		}
		
		private void attach_DANGKYNHOMs(DANGKYNHOM entity)
		{
			this.SendPropertyChanging();
			entity.SINHVIEN = this;
		}
		
		private void detach_DANGKYNHOMs(DANGKYNHOM entity)
		{
			this.SendPropertyChanging();
			entity.SINHVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MOCHUYENDE")]
	public partial class MOCHUYENDE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MACD;
		
		private System.Nullable<int> _MAGIAOVU;
		
		private System.Nullable<bool> _TINHTRANG;
		
		private System.Nullable<System.DateTime> _NGAYMO;
		
		private System.Nullable<System.DateTime> _NGAYDONG;
		
		private EntitySet<DANGKY> _DANGKies;
		
		private EntityRef<CHUYENDE> _CHUYENDE;
		
		private EntityRef<GIAOVU> _GIAOVU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACDChanging(int value);
    partial void OnMACDChanged();
    partial void OnMAGIAOVUChanging(System.Nullable<int> value);
    partial void OnMAGIAOVUChanged();
    partial void OnTINHTRANGChanging(System.Nullable<bool> value);
    partial void OnTINHTRANGChanged();
    partial void OnNGAYMOChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYMOChanged();
    partial void OnNGAYDONGChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYDONGChanged();
    #endregion
		
		public MOCHUYENDE()
		{
			this._DANGKies = new EntitySet<DANGKY>(new Action<DANGKY>(this.attach_DANGKies), new Action<DANGKY>(this.detach_DANGKies));
			this._CHUYENDE = default(EntityRef<CHUYENDE>);
			this._GIAOVU = default(EntityRef<GIAOVU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACD", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MACD
		{
			get
			{
				return this._MACD;
			}
			set
			{
				if ((this._MACD != value))
				{
					if (this._CHUYENDE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMACDChanging(value);
					this.SendPropertyChanging();
					this._MACD = value;
					this.SendPropertyChanged("MACD");
					this.OnMACDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGIAOVU", DbType="Int")]
		public System.Nullable<int> MAGIAOVU
		{
			get
			{
				return this._MAGIAOVU;
			}
			set
			{
				if ((this._MAGIAOVU != value))
				{
					if (this._GIAOVU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAGIAOVUChanging(value);
					this.SendPropertyChanging();
					this._MAGIAOVU = value;
					this.SendPropertyChanged("MAGIAOVU");
					this.OnMAGIAOVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINHTRANG", DbType="Bit")]
		public System.Nullable<bool> TINHTRANG
		{
			get
			{
				return this._TINHTRANG;
			}
			set
			{
				if ((this._TINHTRANG != value))
				{
					this.OnTINHTRANGChanging(value);
					this.SendPropertyChanging();
					this._TINHTRANG = value;
					this.SendPropertyChanged("TINHTRANG");
					this.OnTINHTRANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYMO", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYMO
		{
			get
			{
				return this._NGAYMO;
			}
			set
			{
				if ((this._NGAYMO != value))
				{
					this.OnNGAYMOChanging(value);
					this.SendPropertyChanging();
					this._NGAYMO = value;
					this.SendPropertyChanged("NGAYMO");
					this.OnNGAYMOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYDONG", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYDONG
		{
			get
			{
				return this._NGAYDONG;
			}
			set
			{
				if ((this._NGAYDONG != value))
				{
					this.OnNGAYDONGChanging(value);
					this.SendPropertyChanging();
					this._NGAYDONG = value;
					this.SendPropertyChanged("NGAYDONG");
					this.OnNGAYDONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MOCHUYENDE_DANGKY", Storage="_DANGKies", ThisKey="MACD", OtherKey="MACD")]
		public EntitySet<DANGKY> DANGKies
		{
			get
			{
				return this._DANGKies;
			}
			set
			{
				this._DANGKies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUYENDE_MOCHUYENDE", Storage="_CHUYENDE", ThisKey="MACD", OtherKey="MACD", IsForeignKey=true)]
		public CHUYENDE CHUYENDE
		{
			get
			{
				return this._CHUYENDE.Entity;
			}
			set
			{
				CHUYENDE previousValue = this._CHUYENDE.Entity;
				if (((previousValue != value) 
							|| (this._CHUYENDE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHUYENDE.Entity = null;
						previousValue.MOCHUYENDE = null;
					}
					this._CHUYENDE.Entity = value;
					if ((value != null))
					{
						value.MOCHUYENDE = this;
						this._MACD = value.MACD;
					}
					else
					{
						this._MACD = default(int);
					}
					this.SendPropertyChanged("CHUYENDE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAOVU_MOCHUYENDE", Storage="_GIAOVU", ThisKey="MAGIAOVU", OtherKey="MAGIAOVU", IsForeignKey=true)]
		public GIAOVU GIAOVU
		{
			get
			{
				return this._GIAOVU.Entity;
			}
			set
			{
				GIAOVU previousValue = this._GIAOVU.Entity;
				if (((previousValue != value) 
							|| (this._GIAOVU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GIAOVU.Entity = null;
						previousValue.MOCHUYENDEs.Remove(this);
					}
					this._GIAOVU.Entity = value;
					if ((value != null))
					{
						value.MOCHUYENDEs.Add(this);
						this._MAGIAOVU = value.MAGIAOVU;
					}
					else
					{
						this._MAGIAOVU = default(Nullable<int>);
					}
					this.SendPropertyChanged("GIAOVU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DANGKies(DANGKY entity)
		{
			this.SendPropertyChanging();
			entity.MOCHUYENDE = this;
		}
		
		private void detach_DANGKies(DANGKY entity)
		{
			this.SendPropertyChanging();
			entity.MOCHUYENDE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIKHOAN")]
	public partial class TAIKHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _USERNAME;
		
		private string _PASSWORD;
		
		private EntitySet<GIAOVIEN> _GIAOVIENs;
		
		private EntitySet<GIAOVU> _GIAOVUs;
		
		private EntitySet<SINHVIEN> _SINHVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    #endregion
		
		public TAIKHOAN()
		{
			this._GIAOVIENs = new EntitySet<GIAOVIEN>(new Action<GIAOVIEN>(this.attach_GIAOVIENs), new Action<GIAOVIEN>(this.detach_GIAOVIENs));
			this._GIAOVUs = new EntitySet<GIAOVU>(new Action<GIAOVU>(this.attach_GIAOVUs), new Action<GIAOVU>(this.detach_GIAOVUs));
			this._SINHVIENs = new EntitySet<SINHVIEN>(new Action<SINHVIEN>(this.attach_SINHVIENs), new Action<SINHVIEN>(this.detach_SINHVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(50)")]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this.OnPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD = value;
					this.SendPropertyChanged("PASSWORD");
					this.OnPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_GIAOVIEN", Storage="_GIAOVIENs", ThisKey="USERNAME", OtherKey="USERNAME")]
		public EntitySet<GIAOVIEN> GIAOVIENs
		{
			get
			{
				return this._GIAOVIENs;
			}
			set
			{
				this._GIAOVIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_GIAOVU", Storage="_GIAOVUs", ThisKey="USERNAME", OtherKey="USERNAME")]
		public EntitySet<GIAOVU> GIAOVUs
		{
			get
			{
				return this._GIAOVUs;
			}
			set
			{
				this._GIAOVUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_SINHVIEN", Storage="_SINHVIENs", ThisKey="USERNAME", OtherKey="USERNAME")]
		public EntitySet<SINHVIEN> SINHVIENs
		{
			get
			{
				return this._SINHVIENs;
			}
			set
			{
				this._SINHVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GIAOVIENs(GIAOVIEN entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = this;
		}
		
		private void detach_GIAOVIENs(GIAOVIEN entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = null;
		}
		
		private void attach_GIAOVUs(GIAOVU entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = this;
		}
		
		private void detach_GIAOVUs(GIAOVU entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = null;
		}
		
		private void attach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = this;
		}
		
		private void detach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = null;
		}
	}
}
#pragma warning restore 1591
